---
title: "Untitled"
author: "Jason Torres"
date: "March 23, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup 

```{r}

"%&%" <- function(a,b) paste0(a,b)

library("data.table")
library("tidyverse")
library("grid")
library("gridExtra")
library("viridis")

server.dir <- "/home/jason/science/servers/FUSE5/" 
#server.dir <- "/Users/jtorres/FUSE5/"
work.dir <- server.dir %&% "projects/metaxcan_t2d_v2/"
dat.dir <- work.dir %&% "data_frames/"

loci.df <- fread(dat.dir %&% "gwas_windows.txt") 
assoc.df <- fread(dat.dir %&% "association_results.txt")
islet.df <- fread(dat.dir %&% "islet_association.txt")

plot.dir <- work.dir %&% "plots/"

```

# gene profile data frame 

```{r}

ref.dir <- work.dir %&% "reference_files/"
nhgri.df <- fread(ref.dir %&% "gwas-association-downloaded_2018-02-04-type2diabetes.tsv")
grasp.df <- fread(ref.dir %&% "GRASP_Search_Feb4-2018-T2D-T2D-Pe8.txt")
grasp.ingenes <- grasp.df$InGene %>% unique(.) %>% map(.,function(s){
  out.vec <- c()
  if (grepl(")(",s,fixed=TRUE)){
    vec <- strsplit(s,split=")(",fixed=TRUE)[[1]]
  } else{
    vec <- c(s)
  }
  for (e in vec){
    r <- gsub("(","",e,fixed=TRUE) %>%   gsub(")","",.,fixed=TRUE)
    out.vec <- append(out.vec,r)
  }
  return(out.vec)
}) %>% unlist(.)
grasp.nearest <- grasp.df$NearestGene %>% unique(.) %>% map(.,function(s){
  out.vec <- c()
  if (grepl(")(",s,fixed=TRUE)){
    vec <- strsplit(s,split=")(",fixed=TRUE)[[1]]
  } else{
    vec <- c(s)
  }
  for (e in vec){
    r <- gsub("(","",e,fixed=TRUE) %>%   gsub(")","",.,fixed=TRUE)
    out.vec <- append(out.vec,r)
  }
  return(out.vec)
}) %>% unlist(.)
nhgri.reported <- nhgri.df$`REPORTED GENE(S)` %>% unique(.)  %>% map(.,function(s){
  out.vec <- c()
  if (grepl(", ",s,fixed=TRUE)){
    vec <- strsplit(s,split=", ",fixed=TRUE)[[1]]
  } else{
    vec <- c(s)
  }
  out.vec <- append(out.vec,vec)
  return(out.vec)
}) %>% unlist(.)
manual.vec <- c("C15orf38","AP3S2","CDKN2A","CDKN2B","CTRB1","CTRB2","PROX1","C2CD4A","C2CD4B")
known.vec <- c(grasp.ingenes,grasp.nearest,nhgri.reported,manual.vec) %>% unique(.) 


```





Read in data frames

```{r}



build_table_df <- function(t2d.df,isl.df){
  isl.df$total.replicated <- isl.df$replicated
  isl.df$tissue <- "Islets"
  isl.df$best.tissue <- "---"
  out.df <- rbind(
    dplyr::select(t2d.df,one_of("gene","gene_name","chrom","gene.start",
                                "gene.end","tissue","best.tissue","z","p",
                                "gera.z","gera.p","meta.z","meta.p",
                                "total.replicated","locus")),
    dplyr::select(isl.df,one_of("gene","gene_name","chrom","gene.start",
                                "gene.end","tissue","best.tissue","z","p",
                                "gera.z","gera.p","meta.z","meta.p",
                                "total.replicated","locus")))
  known <- out.df$gene_name %in% known.vec
  out.df$known <- known
  pb <- txtProgressBar(min=0,max=dim(out.df)[1],style=3)
  out.df$t2d.region <- map(1:dim(out.df)[1],function(i){
    setTxtProgressBar(pb,i)
    row.df <- out.df[i,]
    chromo <- row.df$chrom; start <- row.df$gene.start
    end <- row.df$gene.end
    check.df <- filter(loci.df,chrom==chromo,loc.start<end,loc.end>start)
    ifelse(dim(check.df)[1]>0,TRUE,FALSE)
  }) %>% as.logical(.)
  close(pb)
  pb <- txtProgressBar(min=0,max=dim(out.df)[1],style=3)
  out.df$gene.type <- map(1:dim(out.df)[1],function(i){
    setTxtProgressBar(pb,i)
    row.df <- out.df[i,]
    k <- row.df$known; r <- row.df$t2d.region
    ifelse(k==TRUE,"reported",
           ifelse(k==FALSE&r==TRUE,"t2d.region",
                  ifelse(k==FALSE&r==FALSE,"novel.locus",NA)))
  }) %>% as.character(.)
  close(pb)
  out.df <- arrange(out.df,chrom,gene.start) %>% 
    dplyr::select(.,-one_of("known","t2d.region",
                            "gene.start",
                            "gene.end"))
  out.df$tissue <- map(out.df$tissue,function(tiss){
    ifelse(tiss=="cross-tissue","TissueXcan (GTEx)",tiss)
  }) %>% as.character(.)
  out.df$tissue <- map(out.df$tissue,function(s){
    gsub("_","-",s) %>% 
    gsub("islet","Islets",.) %>% 
    gsub("-s","-S",.)}) %>% as.character(.)
  out.df$best.tissue <- map(out.df$best.tissue,function(s){
    gsub("_","-",s) %>% 
    gsub("islet","Islets",.)}) %>% as.character(.)  
  out.df$z <- prettyNum(out.df$z,
                        digits=3)
  out.df$p <- prettyNum(out.df$p,
                        digits=3)
  out.df$gera.z <- prettyNum(out.df$gera.z,
                        digits=3)
  out.df$gera.p <- prettyNum(out.df$gera.p,
                        digits=3)
  out.df$meta.z <- prettyNum(out.df$meta.z,
                        digits=3)
  out.df$meta.p <- prettyNum(out.df$meta.p,
                        digits=3)  
  out.df$best.tissue[is.na(out.df$best.tissue)] <- "---"
  return(out.df)
}


append_bmiadj_info <- function(table.df,sig.gtex,sig.isl){
  df <- c()
  pb <- txtProgressBar(min=0,max=dim(table.df)[1],style=3)
  for (i in 1:dim(table.df)[1]){
    setTxtProgressBar(pb,i)
    row.df <- table.df[i,]
    g <- row.df$gene
    t <- row.df$tissue
    if(t=="Muscle-Skeletal"){
      sub.df <- filter(assoc.df,gene==g) %>% 
        dplyr::select(.,one_of("mus.scottadj.z","mus.scottadj.p"))
      bmiadj.sig <- dim(filter(sig.gtex,gene==g,tissue=="Muscle-skeletal"))[1]>0
    } else if(t=="TissueXcan (GTEx)"){
      sub.df <- filter(assoc.df,gene==g) %>% 
        dplyr::select(.,one_of("multi.scottadj.z","multi.scottadj.p"))
      bmiadj.sig <- dim(filter(sig.gtex,gene==g,tissue=="cross-tissue"))[1]>0
    } else if(t=="Adipose-Subcutaneous"){
      sub.df <- filter(assoc.df,gene==g) %>% 
        dplyr::select(.,one_of("adi.scottadj.z","adi.scottadj.p"))
      bmiadj.sig <- dim(filter(sig.gtex,gene==g,tissue=="Adipose-subcutaneous"))[1]>0
    } else if(t=="Pancreas"){
      sub.df <- filter(assoc.df,gene==g) %>% 
        dplyr::select(.,one_of("panc.scottadj.z","panc.scottadj.p"))
      bmiadj.sig <- dim(filter(sig.gtex,gene==g,tissue=="Pancreas"))[1]>0
    } else if(t=="Liver"){
      sub.df <- filter(assoc.df,gene==g) %>% 
        dplyr::select(.,one_of("liv.scottadj.z","liv.scottadj.p"))
      bmiadj.sig <- dim(filter(sig.gtex,gene==g,tissue=="Liver"))[1]>0
    } else if(t=="Islets" ){
      sub.df <- filter(islet.df,gene==g) %>% 
        dplyr::select(.,one_of("scottadj.z","scottadj.p"))
      bmiadj.sig <- dim(filter(sig.isl,gene==g,tissue=="islet"))[1]>0
    } else{
      print("Error: Please inspect")
    }
    sub.df <- cbind(sub.df,bmiadj.sig)
    names(sub.df) <- c("adj.z","adj.p","adj.sig")
    df <- rbind(df,sub.df)
  }
  close(pb)
  out.df <- cbind(table.df,df)
  out.df$adj.z <- prettyNum(out.df$adj.z,digits=3) 
  out.df$adj.p <- prettyNum(out.df$adj.p,digits=3) 

  return(out.df)
}



append_magic_info <- function(table.df,fg.gtex,fi.gtex,fg.isl,fi.isl){
  df <- c()
  pb <- txtProgressBar(min=0,max=dim(table.df)[1],style=3)
  for (i in 1:dim(table.df)[1]){
    setTxtProgressBar(pb,i)
    row.df <- table.df[i,]
    g <- row.df$gene
    t <- row.df$tissue
    if(t=="Muscle-Skeletal"){
      sub.df <- filter(assoc.df,gene==g) %>% 
        dplyr::select(.,one_of("mus.fg.z","mus.fg.p","mus.fi.z","mus.fi.p"))
      fg.sig <- dim(filter(fg.gtex,gene==g,tissue=="Muscle-skeletal"))[1]>0
      fi.sig <- dim(filter(fi.gtex,gene==g,tissue=="Muscle-skeletal"))[1]>0
    } else if(t=="TissueXcan (GTEx)"){
      sub.df <- filter(assoc.df,gene==g) %>% 
        dplyr::select(.,one_of("multi.fg.z","multi.fg.p","multi.fi.z","multi.fi.p"))
      fg.sig <- dim(filter(fg.gtex,gene==g,tissue=="cross-tissue"))[1]>0
      fi.sig <- dim(filter(fi.gtex,gene==g,tissue=="cross-tissue"))[1]>0    
    } else if(t=="Adipose-Subcutaneous"){
      sub.df <- filter(assoc.df,gene==g) %>% 
        dplyr::select(.,one_of("adi.fg.z","adi.fg.p","adi.fi.z","adi.fi.p"))
      fg.sig <- dim(filter(fg.gtex,gene==g,tissue=="Adipose-subcutaneous"))[1]>0
      fi.sig <- dim(filter(fi.gtex,gene==g,tissue=="Adipose-subcutaneous"))[1]>0    
    } else if(t=="Pancreas"){
      sub.df <- filter(assoc.df,gene==g) %>% 
        dplyr::select(.,one_of("panc.fg.z","panc.fg.p","panc.fi.z","panc.fi.p"))
      fg.sig <- dim(filter(fg.gtex,gene==g,tissue=="Pancreas"))[1]>0
      fi.sig <- dim(filter(fi.gtex,gene==g,tissue=="Pancreas"))[1]>0      
    } else if(t=="Liver"){
      sub.df <- filter(assoc.df,gene==g) %>% 
        dplyr::select(.,one_of("liv.fg.z","liv.fg.p","liv.fi.z","liv.fi.p"))
      fg.sig <- dim(filter(fg.gtex,gene==g,tissue=="Liver"))[1]>0
      fi.sig <- dim(filter(fi.gtex,gene==g,tissue=="Liver"))[1]>0      
    } else if(t=="Islets" ){
      sub.df <- filter(islet.df,gene==g) %>% 
        dplyr::select(.,one_of("fg.z","fg.p","fi.z","fi.p"))
      fg.sig <- dim(filter(fg.isl,gene==g,tissue=="islet"))[1]>0
      fi.sig <- dim(filter(fi.isl,gene==g,tissue=="islet"))[1]>0      
    } else{
      print("Error: Please inspect")
    }
    sub.df <- cbind(sub.df,fg.sig,fi.sig)
    names(sub.df) <- c("fg.z","fg.p","fi.z","fi.p","fg.sig","fi.sig")
    df <- rbind(df,sub.df)
  }
  close(pb)
  out.df <- cbind(table.df,df)
  out.df$fg.z <- prettyNum(out.df$fg.z,digits=3) 
  out.df$fg.p <- prettyNum(out.df$fg.p,digits=3) 
  out.df$fi.z <- prettyNum(out.df$fi.z,digits=3) 
  out.df$fi.p <- prettyNum(out.df$fi.p,digits=3) 

  return(out.df)
}


edit_cell <- function(table, row, col, name="core-fg", ...){
  #http://stackoverflow.com/questions/32173928/r-tablegrob-change-format-of-row
  row <- row + 1 # my adjustment 
  col <- col + 1 # my adjustment
  l <- table$layout
  ids <- which(l$t %in% row & l$l %in% col & l$name==name)
  for (id in ids){
  newgrob <- editGrob(table$grobs[id][[1]], ...)
  table$grobs[id][[1]] <- newgrob
  }
  table
}


plot_table <- function(table.df,outname,start,stop,rep=FALSE,lws=FALSE){

  if(rep==TRUE){
    table.df <- filter(table.df,total.replicated==TRUE)
    if(stop>dim(table.df)[1]){
      stop <- dim(table.df)[1]
    }
    table.df <- table.df[start:stop,]
    
  }
  plot.df <- dplyr::select(table.df,
           -one_of("gene.start","gene.end",
                   "total.replicated","gene.type","fg.sig","fi.sig","locus","adj.sig"))
  plot.df <- dplyr::select(plot.df,one_of("gene","gene_name","chrom","tissue","best.tissue",
                                          "z","p","adj.z","adj.p","gera.z","gera.p","meta.z",
                                          "meta.p","fg.z","fg.p","fi.z","fi.p"))
  if(lws==TRUE){
    plot.df$locus <- table.df$locus
    names(plot.df) <- c("Ensembl","Symbol","Chr","Tissue","Top Tissue\n(TissueXcan)",
                        "Z-score","P-value","Z-score\n(BMI adj.)","P-value\n(BMI adj.)","Z-score\n(GERA)","P-value\n(GERA)",
                        "Z-score\n(Meta-analysis)","P-value\n(Meta-analysis)",
                        "Z-score\n(FG)","P-value\n(FG)",
                        "Z-score\n(FI)","P-value\n(FI)",
                        "Region")    
  } else{
    names(plot.df) <- c("Ensembl","Symbol","Chr","Tissue","Top Tissue\n(TissueXcan)",
                        "Z-score","P-value","Z-score\n(BMI adj.)","P-value\n(BMI adj.)","Z-score\n(GERA)","P-value\n(GERA)",
                        "Z-score\n(Meta-analysis)","P-value\n(Meta-analysis)",
                        "Z-score\n(FG)","P-value\n(FG)",
                        "Z-score\n(FI)","P-value\n(FI)")    
  }
  mytheme <- gridExtra::ttheme_default(
    core = list(fg_params=list(cex = 0.7),
    bg_params=list(fill="ghostwhite",alpha=0.3,
                   col="black")),
    colhead = list(fg_params=list(cex = 0.9),
    bg_params=list(alpha=0.30,col="black")),
    rowhead = list(fg_params=list(cex = 0))) 
  
  if(rep==FALSE){
    plot.df <- plot.df[start:stop,]
    table.df <- table.df[start:stop,]
  }
  tabgrob <- tableGrob(plot.df,
                      theme=mytheme) 
  tabgrob <- edit_cell(tabgrob, row=1:dim(plot.df)[1], 
                       col=2, "core-fg", 
                 gp=gpar(fontface="italic")) 
  vec <- c(1:dim(plot.df)[1])[table.df$total.replicated]
 
  rep.vec <- c(1:dim(table.df)[1])[table.df$gene.type=="reported"] %>% na.omit(.)
  reg.vec <- c(1:dim(table.df)[1])[table.df$gene.type=="t2d.region"] %>% na.omit(.)
  nov.vec <- c(1:dim(table.df)[1])[table.df$gene.type=="novel.locus"] %>% na.omit(.)
  fg.vec <- c(1:dim(table.df)[1])[table.df$fg.sig] %>% na.omit(.)
  fi.vec <- c(1:dim(table.df)[1])[table.df$fi.sig] %>% na.omit(.)
  adj.vec <- c(1:dim(table.df)[1])[table.df$adj.sig] %>% na.omit(.)
  replic.vec <- c(1:dim(table.df)[1])[table.df$total.replicated] %>% na.omit(.)

  tabgrob <- edit_cell(tabgrob, row=adj.vec, col=c(8,9), "core-fg", 
                 gp=gpar(fontface="bold"))    
  tabgrob <- edit_cell(tabgrob, row=replic.vec, col=c(10,11), "core-fg", 
                 gp=gpar(fontface="bold")) 
  tabgrob <- edit_cell(tabgrob, row=replic.vec, col=c(12,13), "core-fg", 
                 gp=gpar(fontface="bold")) 
  tabgrob <- edit_cell(tabgrob, row=replic.vec, col=2, "core-fg", 
                 gp=gpar(fontface="bold.italic")) 
  tabgrob <- edit_cell(tabgrob, row=fg.vec, col=c(14,15), "core-fg", 
                 gp=gpar(fontface="bold")) 
  tabgrob <- edit_cell(tabgrob, row=fi.vec, col=c(16,17), "core-fg", 
                 gp=gpar(fontface="bold")) 
  
  tabgrob <- edit_cell(tabgrob, row=rep.vec, col=c(1:dim(plot.df)[2]), "core-bg", 
                 gp=gpar(fill=viridis(2)[1],alpha=0.5, 
                         col =viridis(2)[1], lwd=1))  
  tabgrob <- edit_cell(tabgrob, row=reg.vec, c(1:dim(plot.df)[2]), "core-bg", 
                 gp=gpar(fill=viridis(2)[2],alpha=0.5, 
                         col =viridis(2)[2], lwd=1))
  tabgrob <- edit_cell(tabgrob, row=nov.vec, c(1:dim(plot.df)[2]), "core-bg", 
                 gp=gpar(fill="grey",alpha=0.5, 
                         col ="grey", lwd=1))   
  ggsave(tabgrob,file=outname,
         height=20,width=20)
}

```


# Scott T2D (full and replicated-only)

## GWS

```{r}

scott.df <- fread(dat.dir %&% "Scott_T2D_gws-significant.full.txt")
scott.islet <- fread(dat.dir %&% "Scott_T2D_gws-significant_Islet.txt")
scott.islet$gene_name[13] <- "EGFEM1P"; scott.islet$gene.start[13] <- 167967729 ; scott.islet$gene.end[13] <- 168539123;
scott.islet$chrom[13] <- 3
names(scott.islet)[names(scott.islet)=="scott.z"] <- "z"
names(scott.islet)[names(scott.islet)=="scott.p"] <- "p"

adj.df <- fread(dat.dir %&% "Scott_T2D_BMIadj_gws-significant.txt") 
adj.islet <- fread(dat.dir %&% "Scott_T2D_BMIadj_gws-significant_Islet.txt") 


fg.sig.gtex <- fread(dat.dir %&% "Magic_FG_gws-significant.txt")
fi.sig.gtex <- fread(dat.dir %&% "Magic_FI_gws-significant.txt")
fg.sig.isl <- fread(dat.dir %&% "Magic_FG_gws-significant_Islet.txt")
fg.sig.isl$tissue <- "islet"
fi.sig.isl <- fread(dat.dir %&% "Magic_FI_gws-significant_Islet.txt")
fi.sig.isl$tissue <- "islet"

table.df <- build_table_df(scott.df,scott.islet) %>% append_bmiadj_info(.,adj.df,adj.islet) %>% 
  append_magic_info(.,fg.sig.gtex,data.frame(),
                              fg.sig.isl,data.frame())


write.table(x=table.df,file=dat.dir%&%"result-table_ScottT2D_gws.txt",
            sep="\t",quote=FALSE,row.names=FALSE)

plot_table(table.df,plot.dir%&%"result-table_ScottT2D_gws_full.png",
           start=1,stop=dim(table.df)[1],rep=FALSE)
plot_table(table.df,plot.dir%&%"result-table_ScottT2D_gws_replicated.png",
           start=1,stop=dim(table.df)[1],rep=TRUE)
```


# Scott T2D (full and replicated-only)

## LWS

```{r}

scott.df <- fread(dat.dir %&% "Scott_T2D_lws-significant.full.txt")
scott.islet <- fread(dat.dir %&% "Scott_T2D_lws-significant_Islet.txt")

fg.sig.gtex <- fread(dat.dir %&% "Magic_FG_lws-significant.txt")
fi.sig.gtex <- fread(dat.dir %&% "Magic_FI_lws-significant.txt")
fg.sig.isl <- fread(dat.dir %&% "Magic_FG_lws-significant_Islet.txt")
fg.sig.isl$tissue <- "islet"
fi.sig.isl <- fread(dat.dir %&% "Magic_FI_lws-significant_Islet.txt")
fi.sig.isl$tissue <- "islet"

names(scott.islet)[names(scott.islet)=="scott.z"] <- "z"
names(scott.islet)[names(scott.islet)=="scott.p"] <- "p"

adj.df <- fread(dat.dir %&% "Scott_T2D_BMIadj_lws-significant.txt") 
adj.islet <- fread(dat.dir %&% "Scott_T2D_BMIadj_lws-significant_Islet.txt") 
adj.islet$tissue <- "islet"


table.df <-  build_table_df(scott.df,scott.islet) %>% append_bmiadj_info(.,adj.df,adj.islet) %>% 
  append_magic_info(.,fg.sig.gtex,fi.sig.gtex,
                              fg.sig.isl,fi.sig.isl)

# 166 rows total 


write.table(x=table.df,file=dat.dir%&%"result-table_ScottT2D_lws.txt",
            sep="\t",quote=FALSE,row.names=FALSE)

plot_table(table.df,plot.dir%&%"result-table_ScottT2D_lws_replicated.png",
           start=1,stop=dim(table.df)[1],rep=TRUE,lws=TRUE)
plot_table(table.df,plot.dir%&%"result-table_ScottT2D_lws_full_part1.png",
           start=1,stop=45,rep=FALSE,lws=TRUE)
plot_table(table.df,plot.dir%&%"result-table_ScottT2D_lws_full_part2.png",
           start=46,stop=90,rep=FALSE,lws=TRUE)
plot_table(table.df,plot.dir%&%"result-table_ScottT2D_lws_full_part3.png",
           start=91,stop=136,rep=FALSE,lws=TRUE)
plot_table(table.df,plot.dir%&%"result-table_ScottT2D_lws_full_part4.png",
           start=137,stop=181,rep=FALSE,lws=TRUE)

```
 






